# Generated by Django 5.2.12 on 2026-03-25 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.asset'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='portfolio.portfolio'),
        ),
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.portfolio'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['portfolio', 'active'], name='portfolio_a_portfol_1b25f0_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['date'], name='portfolio_p_date_ee4f09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliosnapshot',
            unique_together={('portfolio', 'date')},
        ),
    ]
